language: node_js
sudo: true

services:
  - docker

branches:
  only:
    - master

script: git config --global user.email "prishelec@gmail.com" && git config --global user.name "Leonti" && bash publish.sh
