version: '2'
services:
  home-ui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST_PORT
      - MONGO_DB
      - MONGO_USERNAME
      - MONGO_PASSWORD
    ports:
      - "4000:3003"
